packages:
  all:
    providers:
      gl: [apple-opengl]
      glu: [apple-glu]
      mpi: [mpich~fortran]
      blas: [openblas~lapack]
      lapack: [openblas~lapack]
  openblas:
    variants: ~lapack
  # python:
  #   version: ['3.9.1:']
  root:
    variants: +aqua ~x ~tbb +monalisa +http +dataframe +arrow cxxstd=17
