packages:
  all:
    variants: cxxstd=17
  llvm:
    variants: ~lldb +compiler-rt +clang +llvm_dylib
  root:
    variants: ~tbb +monalisa +http +dataframe +arrow cxxstd=17
  boost:
    version: [':1.74']

